### ISSUE TITLE
MicroService to Update an installer package

### ISSUE THREAD

**Issue by revred** [oll3/bita#21]
I am new to rust and am interested in using this crate for a project. I was able to build the source code on VS Code but unable to run it and get an "unknown error" when I try and run. I suspect I am not using it right. Is it possible to have a small section for newbies like me to get started with bita on visual studio code. I am also running this on windows. The real goal is to allow beta to manage installer packages by only delivering the incremental changes from the previous vetsion.

**Comment by oll3** [comment]
Hi and welcome @revred !

Is that the exact output of bita on the main git branch?
If I run bita without any command I get:
```shell
olle@computer:~$ bita
Error: Unknown command
```
`bita -h`/ `bita --help` would yield some more info about the available sub-commands.

I'm not running windows but I wouldn't expect any main differences in output. And working with bita in vscode shouldn't be different to any other Rust project AFAIK. I use vscode with the rust-analyzer extension myself.

Only other thing I can think of, which I don't know how it would show on windows, is if linking with the default/native tls library fails somehow. You could possibly try building with `rustls` for tls backend instead; `cargo build --no-default-features --features rustls-tls`.

**Comment by revred** [comment]
![image](https://user-images.githubusercontent.com/31846057/153587755-c35c2f65-c10c-440a-98fd-1677cc92441d.png)

Please find the output as above. Let me know if you need more details. Happy to share.

**Comment by revred** [comment]
> Hi and welcome @revred !
> 
> Is that the exact output of bita on the main git branch? If I run bita without any command I get:
> 
> ```shell
> olle@computer:~$ bita
> Error: Unknown command
> ```
> 
> `bita -h`/ `bita --help` would yield some more info about the available sub-commands.
> 
> I'm not running windows but I wouldn't expect any main differences in output. And working with bita in vscode shouldn't be different to any other Rust project AFAIK. I use vscode with the rust-analyzer extension myself.
> 
> Only other thing I can think of, which I don't know how it would show on windows, is if linking with the default/native tls library fails somehow. You could possibly try building with `rustls` for tls backend instead; `cargo build --no-default-features --features rustls-tls`.

Thanks for the warm welcome :)
OK, Let me try this. Thanks. I may have not understood the usage very well.

**Comment by revred** [comment]
Thanks - understood.

I have made some progress since.

![image](https://user-images.githubusercontent.com/31846057/153600921-e8c475d8-cca5-4e82-80f9-4e363204efce.png)

I am trying to clone a document using a seed. Here is my attempt. Am I feeding multiple seeds where I may want to say I justa have 1 seed, 1 input, and 1 expected output? How do I do this?
Apologies if this is too trivial and I am wasting your time!

**Comment by oll3** [comment]
Hm, I see. Think that is actually something we might want to change. Right now multiple seeds can be given without repeating `--seed`, like `--seed seed1 seed2 seed3`, hence --seed has to go as last parameter or your input and output will be seen as seed files. I think it would be better if one were forced to repeat --seed for each given seed. But will look into this later.

Another thing (just guessing based on your file endings) but the seeds you are giving should typically not be files compressed by bita. It's not wrong but bita will probably not find a lot to re-use there since it doesn't really understand or care about file formats when scanning seed files.
A seed should typically be an uncompressed 'version' of the file you want to clone. By version I mean that it might not be the exact file your cloning but it is a file that may contain data similar to the cloned file. If that makes any sense to you.

**Comment by oll3** [comment]
Since commit ac49759e0f23138cc2dbb2f02fda096f753691c8 bita will also show cli help if it's being run without argument. This instead of just saying "Error: unknown command".
Closing issue since with that I think it has been resolved, if there ever was an issue to begin with. :)
