### ISSUE TITLE
Allowing other filesystem types, in particular SMB2

### ISSUE THREAD

**Issue by rkhwaja** [oll3/bita#26]
It looks like what you need from a remote filesystem is efficient read-only range requests, so it should be possible to support SMB2 as the remote filesystem.

**Comment by oll3** [comment]
Hi @rkhwaja,

At this time there is no particular filesystem support in bita. It can only clone from a http hosted archive or a local archive (a file).

If you're asking to clone from a remote smb filesystem instead of http, then one way could be to mount the smb filesystem on the target. Since bita can clone from local archives this should already work.

If you are asking for native support to clone from a remote smb filesystem I would say it is probably possible but I'm not sure it's something I want to develop or maintain at this time.
If it's something you're really interested in to develop and help maintain I would suggest to start it as a 3rd party crate and we can take it from there. One way to go about it could be to use curl as a backend (instead of reqwest) since it has at least some support for smb.

**Comment by oll3** [comment]
Closing since it's unclear to me what's being requested and no further activity from author.
